server:
  port: 7071



spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/city
    username: postgres
    password: ShababSpara


  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update



